language: python
python:
    - "3.5"
    - "3.6"
    - "3.7"
install:
    - pip install behave
    - pip install flask
    - pip install markovify
    - pip install pylama
    - pip install coveralls
script:
    - behave
    - pylama features/ friendbot/ setup.py --skip friendbot/__init__.py
    - coverage run --include="./friendbot/*" -m behave
after_success: coveralls
