language: python
dist: bionic
python:
  - '3.7'
services:
  - docker
git:
  depth: 3
cache:
  - pip
addons:
  apt:
    packages:
      - docker-ce
jobs:
  include:
    - stage: "Build, Test, Deploy"
      script:
        - docker build -t barrelmaker97/friendbot:amd64 .
      script:
        - docker run --rm --privileged multiarch/qemu-user-static:register
        - wget https://github.com/multiarch/qemu-user-static/releases/download/v4.1.0-1/qemu-arm-static.tar.gz -O ./qemu-arm-static.tar.gz
        - tar zxvf ./qemu-arm-static.tar.gz -C ./
        - docker build -t barrelmaker97/friendbot:arm --build-arg BASE_IMAGE=arm32v7/python:3.7-alpine .
      script:
        - pip install flask markovify requests behave coveralls
        - coverage run --include="./friendbot/*" -m behave
        - coveralls
      deploy:
        provider: script
        script: bash deploy.sh
    - stage: "Deploy Manifest"
      script:
        - export DOCKER_CLI_EXPERIMENTAL=enabled
        - echo "$DOCKER_PASSWORD" | docker login -u "barrelmaker97" --password-stdin
        - docker manifest create barrelmaker97/friendbot:latest barrelmaker97/friendbot:amd64 barrelmaker97/friendbot:arm
        - docker manifest annotate barrelmaker97/friendbot:latest barrelmaker97/friendbot:amd64 --arch amd64
        - docker manifest annotate barrelmaker97/friendbot:latest barrelmaker97/friendbot:arm --arch arm
        - docker manifest push barrelmaker97/friendbot:latest
