language: minimal
services:
  - docker
git:
  depth: 3
jobs:
  include:
    - stage: "amd64"
      dist: bionic
      addons:
        apt:
          packages:
            - docker-ce
      env:
        - IMAGE_TAG=amd64
      script:
        - docker build -t barrelmaker97/friendbot:$IMAGE_TAG .
      deploy:
        provider: script
        script: bash deploy.sh
    - stage: "arm"
      os: linux
      arch: arm64
      env:
        - IMAGE_TAG=arm
      script:
        - docker build -t barrelmaker97/friendbot:$IMAGE_TAG --build-arg BASE_IMAGE=arm32v7/python:3.7-alpine .
      deploy:
        provider: script
        script: bash deploy.sh
        edge: true
