language: python
dist: bionic
python:
  - '3.7'
env:
  - BASE_IMAGE=python:3.7-alpine IMAGE_TAG=amd64
  - BASE_IMAGE=arm32v7/python:3.7-alpine IMAGE_TAG=arm32v7
services:
  - docker
before_install:
  - docker-setup.sh
git:
  depth: 3
cache: pip
install:
  - pip install flask markovify requests behave pylama coveralls black
script:
  - black --check --diff friendbot features
  - pylama features friendbot
  - coverage run --include="./friendbot/*" -m behave
deploy:
  provider: script
  script: bash deploy.sh
