language: python
dist: bionic
python:
  - '3.7'
services:
  - docker
git:
  depth: 3
cache:
  - pip
addons:
  apt:
    packages:
      - docker-ce
jobs:
  include:
    - stage: "Build, Test, Deploy"
      env:
        - BASE_IMAGE=python:3.7-alpine IMAGE_TAG=amd64
      env:
        - BASE_IMAGE=arm32v7/python:3.7-alpine IMAGE_TAG=arm
      before_install:
        - bash docker-setup.sh
      install:
        - pip install flask markovify requests behave coveralls black
      script:
        - black --check --diff friendbot features
        - coverage run --include="./friendbot/*" -m behave
      after_success:
        - coveralls
      deploy:
        provider: script
        script: bash deploy.sh
    - stage: "Deploy Manifest"
      script: manifest.sh
