language: python
dist: bionic
python:
- '3.7'
services:
- docker
before_install:
- docker build -t $DOCKER_USERNAME/friendbot .
git:
  depth: 3
cache: pip
install:
- pip install flask markovify requests behave pylama coveralls black
script:
- black --check --diff friendbot features
- pylama features friendbot
- coverage run --include="./friendbot/*" -m behave
after_success:
- coveralls
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push $DOCKER_USERNAME/friendbot:latest
