language: python
dist: bionic
python:
  - '3.7'
services:
  - docker
git:
  depth: 3
cache:
  - pip
addons:
  apt:
    packages:
      - docker-ce
jobs:
  include:
    - stage: "Build, Test, Deploy - amd64"
      env:
        - IMAGE_TAG=amd64
      script:
        - docker build -t barrelmaker97/friendbot:$IMAGE_TAG .
      deploy:
        provider: script
        script: bash deploy.sh
    - stage: "Build, Test, Deploy - arm"
      env:
        - IMAGE_TAG=arm
      install:
        - docker run --rm --privileged multiarch/qemu-user-static:register
        - wget https://github.com/multiarch/qemu-user-static/releases/download/v4.1.0-1/qemu-arm-static.tar.gz -O ./qemu-arm-static.tar.gz
        - tar zxvf ./qemu-arm-static.tar.gz -C ./
      script:
        - docker build -t barrelmaker97/friendbot:$IMAGE_TAG --build-arg BASE_IMAGE=arm32v7/python:3.7-alpine .
      deploy:
        provider: script
        script: bash deploy.sh
