language: python
dist: bionic
python:
  - '3.7'
services:
  - docker
git:
  depth: 3
cache:
  - pip
addons:
  apt:
    packages:
      - docker-ce
jobs:
  include:
    - stage: "Build, Test, Deploy - amd64"
      env:
        - BASE_IMAGE=python:3.7-alpine IMAGE_TAG=amd64
      before_install:
        - bash docker-setup.sh
      install:
        - pip install flask markovify requests behave coveralls black
      script:
        - black --check --diff friendbot features
        - coverage run --include="./friendbot/*" -m behave
      after_success:
        - coveralls
      deploy:
        provider: script
        script: bash deploy.sh
    - stage: "Build, Test, Deploy - arm"
      env:
        - BASE_IMAGE=arm32v7/python:3.7-alpine IMAGE_TAG=arm
      before_install:
        - bash docker-setup.sh
      install:
        - pip install flask markovify requests behave coveralls black
      script:
        - black --check --diff friendbot features
        - coverage run --include="./friendbot/*" -m behave
      after_success:
        - coveralls
      deploy:
        provider: script
        script: bash deploy.sh
    - stage: "Deploy Manifest"
      script:
        - export DOCKER_CLI_EXPERIMENTAL=enabled
        - docker manifest create barrelmaker97/friendbot:latest barrelmaker97/friendbot:amd64 barrelmaker97/friendbot:arm
        - docker manifest annotate barrelmaker97/friendbot:latest barrelmaker97/friendbot:amd64 --arch amd64
        - docker manifest annotate barrelmaker97/friendbot:latest barrelmaker97/friendbot:arm --arch arm
        - docker manifest push barrelmaker97/friendbot:latest
