language: python
dist: bionic
python:
  - '3.7'
services:
  - docker
before_install:
  - docker build -t barrelmaker97/friendbot .
  - docker run -d -v $(realpath ./test_data/export):/export barrelmaker97/friendbot
git:
  depth: 3
cache: pip
install:
  - pip install flask markovify requests behave pylama coveralls black
script:
  - black --check --diff friendbot features
  - pylama features friendbot
  - coverage run --include="./friendbot/*" -m behave
deploy:
  provider: script
  script: bash deploy.sh
