version: "3.7"
services:
  app:
    image: "test:latest"
    ports:
      - "5000:5000"
    volumes:
      - type: bind
        source: ${FB_EXPORT}
        target: /export
        read_only: true
    restart: always
  redis:
    image: "redis:alpine"
